### ISSUE TITLE
Simplify/Fix directional collision

### ISSUE THREAD

**Issue by mkr-mac** [CorruptData/Breakout#1]
The collision still does not work properly, and is a total mess.

**Comment by WJLiddy** [comment]
Let's write the pseudocode for this on Saturday. Then you can implement it.

**Comment by mkr-mac** [comment]
Went and completely broke collision this update (somewhat intentionally), and will probably redo it soon.

**Comment by mkr-mac** [comment]
Fixed with Jack's help.
