### ISSUE TITLE
Create way to design levels

### ISSUE THREAD

**Issue by mkr-mac** [CorruptData/Breakout#11]
There is currently no good way to put blocks for a level in any way except one large rectangle. I'm debating whether to make some sort of text/xml entry format, or to make a level editor in the game.

**Comment by WJLiddy** [comment]
Use an XML with Coords, maybe? For example <1-1> = BLUE  <2-1> = RED

**Comment by mkr-mac** [comment]
This sort of system will probably work. Will look into reading from XMLs and getting data from them.

**Comment by mkr-mac** [comment]
Changed bricks to work as a linked list in preparation for this change.

**Comment by mkr-mac** [comment]
XML method now works.
