### ISSUE TITLE
Implement color tinted blocks

### ISSUE THREAD

**Issue by WJLiddy** [CorruptData/Breakout#7]
The API has been updated. You may now tint an animation by specifying the color as the last argument.
For example, to color all your bricks blue, on line 51 of Bricks.cs:

brick.draw(sb, (i \* width) + spaceX, (j \* height) + spaceY, brickColor[i,j]);

Personally I think the bricks look best as Blanched Almond or Pale Goldenrod

**Comment by mkr-mac** [comment]
Made the blocks PaleGodenrod. Will probably do more later, but it works now!
